Números e numerais - Raissa
tupaschoal/TED-Translators_PT-BR_Styleguide pull request #10
Opened 2016-12-11 20:47 UTC by Raissarrm

1. Acho que o exemplo  "Dois, dez, 300" pode confundir, uma vez que, na prática, como se explica a seguir no Guia, daríamos um jeito de usar algo como "2, 10, 300", para evitar misturar as regras numa mesma frase.
2. Que tal dar um exemplo de "qualquer potência de dez" nos número ordinais?
3. Este exemplo:
- Numa sequência de porcentagens, sempre repetir o símbolo %:
>> "As taxas de juros variam entre 5% e 7%."

Não estaria conflitando com este outro exemplo?
Quando o palestrante usar vários números de porcentagem numa mesma fala, mantenha o símbolo somente no último. Por exemplo:
"Os resultados indicam que 10 a 15% dos jovens brasileiros..."

4. Fiquei na dúvida com o uso do ordinal (dentro do exemplo dos romanos). Este exemplo aqui:
"em seu artigo 5º" 

não estaria conflitando com este?

Escreva por extenso números ordinais até dez e qualquer potência de dez. Para números maiores que dez, use os algarismos mais o símbolo "ª" ou "º". Por exemplo:
- Primeiro

Ou estaríamos considerando que, como os romanos são sempre usados em algarismos (nunca por extenso), os demais números que estiverem na frase acompanham esse raciocínio?
Este exemplo do artigo me gerou uma outra dúvida: será que devemos escrever "artigo quinto", "inciso nono", etc. ao citar leis, por exemplo?
Quem sabe deixamos os ordinais todos na forma de algarismos?

2016-12-11 21:12 UTC, tupaschoal requested changes
Algumas mudanças pequenas. Sobre o que comentou:
1 - Concordo, pode mudar, não era para interpretarem o "Dois, dez, 300" como uma legenda, mas posso ver pessoas confundindo mesmo.
2 - Pode colocar (ou você está me perguntando?, fiquei na dúvida :) )
3 - Correto. O manual do SECOM diz para repetir, deveríamos suprimir a primeira recomendação então.
4 - Nunca tinha parado para refletir. Acho um ótimo ponto para levantarmos no grupo de LCs.

2016-12-11 21:12 UTC, tupaschoal commented on docs/numeros_numerais.md
> +Ou reescreva a frase:"
Tem um símbolo de aspas perdido no fim da linha.

2016-12-11 21:12 UTC, tupaschoal commented on docs/numeros_numerais.md
> +"Faltaram hoje 25% dos alunos."
Adicione um ">" ao início da linha para manter a formatação.

2016-12-11 21:12 UTC, tupaschoal commented on docs/numeros_numerais.md
> +> "Quinze pessoas se salvaram/foram salvas. Ou: "Salvaram-se 15 pessoas"/"Foram salvas 15 pessoas".
Faltou o símbolo das aspas ao fim da primeira frase.

2016-12-11 21:12 UTC, tupaschoal commented on docs/numeros_numerais.md
> +> "Shakespeare nasceu no século 16."
Bom exemplo :)

2016-12-24 12:18 UTC, merged

2016-12-24 19:53 UTC, Raissarrm commented on docs/numeros_numerais.md
> +"Faltaram hoje 25% dos alunos."
Oi, Túlio, estou olhando com calma as alterações do Guia e notei que algumas não foram feitas.

É preciso fazer algum procedimento para atualizar o Guia?

Ou talvez eu devesse ter feito as alterações, como você me orientou, para facilitar, em vez de apenas sugeri-las.

Como apenas sugeri, sem alterar o texto, não foi gerado rascunho para você aceita-las ou não.

Bem, na parte dos numerais, notei o seguinte:

1. No caso do "dois, dez, 300", penso que o ideal seria dar exemplos separados para ficar bem claro o uso desses numerais dentro da frase:

"Para o teste, não importa se são duas ou dez pessoas, o resultado é o mesmo."
"Para o teste, não importa se são 11 ou 300 pessoas, o resultado será o mesmo."

2. No caso da potência de 10, na verdade não entendi o que o Guia queria dizer e estava querendo que você sugerisse um exemplo para ficar claro. 

3. No caso da porcentagem, ficaram os dois exemplos. A intenção era suprimir o primeiro exemplo, certo?

Quando o palestrante usar vários números de porcentagem numa mesma fala, mantenha o símbolo somente no último. Por exemplo:
"Mais de 25% das mulheres entrevistadas disseram..."
"Os resultados indicam que 10 a 15% dos jovens brasileiros..."

Numa sequência de porcentagens, sempre repetir o símbolo %:
"As taxas de juros variam entre 5% e 7%."
Bem, vou continuar a ler aos poucos o resto, ok? 

Estou achando que você fez as alterações, mas, por algum motivo, não houve uma atualização. 

Um abraço,

Raissa

2016-12-24 20:12 UTC, tupaschoal commented on docs/numeros_numerais.md
> +"Faltaram hoje 25% dos alunos."
Oi Raissa,

Pois é, se você não editou o arquivo, então nada deveria ter mudado. No caso, eu li todas as sugestões e implementei quase todas, a das porcentagens, por exemplo, foi uma delas (https://github.com/tupaschoal/TED-Translators_PT-BR_Styleguide/blob/master/docs/numeros_numerais.md#porcentagem)

Você está certa quando desconfia de o site não ter atualizado. Subi as mudanças, mas não gerei o site atualizado ainda, devo fazer isso só amanhã à noite! O jeito de garantir que está lendo as versões mais recentes é indo direto ao arquivo aqui: https://github.com/tupaschoal/TED-Translators_PT-BR_Styleguide/tree/master/docs

Abraço

2016-12-24 20:29 UTC, Raissarrm commented
Ah... então, tá!
Deve ser isso então.
Vou deixar para ler tudo depois que você atualizar então.
Obrigada, Túlio! :)

 

    Em Sábado, 24 de Dezembro de 2016 18:12, Tulio Leao <notifications@github.com> escreveu:
 

 @tupaschoal commented on this pull request.In docs/numeros_numerais.md:>  
-> "Vinte e cinco por cento dos alunos faltaram hoje. (Em vez de: 25% dos alunos faltaram hoje)"
-
-> "Mil e quinhentos ingressos foram vendidos aos torcedores. / Venderam 1,5 mil ingressos aos torcedores."
-
-> "Quinze pessoas se salvaram/foram salvas. Ou: Salvaram-se 15 pessoas/Salvaram 15 pessoas."
+> "Vinte e cinco por cento dos alunos faltaram hoje." (Em vez de: 25% dos alunos faltaram hoje)"
+Ou reescreva a frase:"
+"Faltaram hoje 25% dos alunos."
Oi Raissa,Pois é, se você não editou o arquivo, então nada deveria ter mudado. No caso, eu li todas as sugestões e implementei quase todas, a das porcentagens, por exemplo, foi uma delas (https://github.com/tupaschoal/TED-Translators_PT-BR_Styleguide/blob/master/docs/numeros_numerais.md#porcentagem)Você está certa quando desconfia de o site não ter atualizado. Subi as mudanças, mas não gerei o site atualizado ainda, devo fazer isso só amanhã à noite! O jeito de garantir que está lendo as versões mais recentes é indo direto ao arquivo aqui: https://github.com/tupaschoal/TED-Translators_PT-BR_Styleguide/tree/master/docsAbraço—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.