Update transcricoes.md
tupaschoal/TED-Translators_PT-BR_Styleguide pull request #6
Opened 2016-12-04 22:28 UTC by Raissarrm

Oi, Túlio! Estou propondo algumas alterações. Espero que não tenha bagunçado seu trabalho tão caprichado. Vamos ver se dá certo. :)

2016-12-04 22:54 UTC, tupaschoal requested changes
Oi Raissa,

Ótimas alterações, fiz alguns comentários só que basicamente se resumem a não fazer os comentários no arquivo, porque aí vai aparecer na página. Usa o campo de explicar o porque do pull request e tal. Mas é bem isso que vc fez mesmo, só tira os comentários que eu aceito o request.

2016-12-04 22:54 UTC, tupaschoal commented on docs/transcricoes.md
> +Transcrever é o ato de redigir um texto que assimile a fala do palestrante, tal como ele a reproduz.(Eu devo ter escrito isso, mas agora estou achando um pouqo estranho esse "tal como ele a reproduz"
Se achar estranho, pode tirar. Mas tira o comentário, senão ele vai aparecer na página :)

2016-12-04 22:54 UTC, tupaschoal commented on docs/transcricoes.md
> +Tenha o devido cuidado de evitar sílabas vazias, repetições ou tropeços do palestrante. Caso haja um erro óbvio, pode-se corrigi-lo, desde que a correção esteja entre colchetes, para indicar que não
A mesma coisa que disse no outro, altere o que for preciso e faça os comentários fora do arquivo.

2016-12-04 22:54 UTC, tupaschoal commented on docs/transcricoes.md
> +TULIO, apesar de óbvio para nós, acho que seria bom colocar, na frente dessas frases, algo como "Correto" e "Errado"
Concordo, não estava muito satisfeito com a solução atual, essa parece boa. (Remove esse comentário do código depois :) )

2016-12-04 22:54 UTC, tupaschoal commented on docs/transcricoes.md
> +- Quando ficar óbvio o engano em casos como, por exemplo, o palestrante dizer “baixo” claramente querendo dizer “alto”, e a edição for alterar de maneira considerável o significado da sentença, coloq
Não seria disser?

2016-12-05 01:14 UTC, Raissarrm commented
Tem razão, Túlio: disser. 

    Em Domingo, 4 de Dezembro de 2016 20:54, Tulio Leao <notifications@github.com> escreveu:
 

 @tupaschoal requested changes on this pull request.Oi Raissa,Ótimas alterações, fiz alguns comentários só que basicamente se resumem a não fazer os comentários no arquivo, porque aí vai aparecer na página. Usa o campo de explicar o porque do pull request e tal. Mas é bem isso que vc fez mesmo, só tira os comentários que eu aceito o request.In docs/transcricoes.md:> @@ -1,10 +1,10 @@
 # Transcrições
 
 ## Distinção entre Tradução e Transcrição
-Transcrever é o ato de redigir um texto que assimile a fala do palestrante, tal como ele a reproduz. É importante que contenha, com a máxima fidelidade possível, as palavras deste.
+Transcrever é o ato de redigir um texto que assimile a fala do palestrante, tal como ele a reproduz.(Eu devo ter escrito isso, mas agora estou achando um pouqo estranho esse "tal como ele a reproduz". Reproduzir dá a ideia de "produzir novamente" "copiar" etc.) É importante que contenha, com a máxima fidelidade possível, as palavras deste.
Se achar estranho, pode tirar. Mas tira o comentário, senão ele vai aparecer na página :)In docs/transcricoes.md:>  Assim, para evitar descaracterizar a fala dos palestrantes que utilizam uma linguagem mais coloquial, serão aceitas algumas formas gramaticais que, apesar de não serem abonadas num texto formal culto, são adequadas e próprias num contexto mais informal.
 
-Tenha o devido cuidado de evitar sílabas vazias, repetições ou tropeços do palestrante. Caso haja um erro óbvio, pode-se corrigi-lo, desde que a correção esteja entre colchetes, para indicar que não foi o que ele disse. Também é aceitável reescrever o que o palestrante disse em casos onde se precise adequar a legenda para que tenha velocidade de leitura e comprimento adequados. A transcrição de legendas também deve incluir informações sonoras como aplausos e risos, para os deficientes auditivos, tal como a sincronia com a fala do palestrante. Traduções ocorrem quando a palestra foi ministrada em um idioma estrangeiro que não seja o Português Brasileiro, caso em que utilizamos uma transcrição do idioma original como texto base para a criação da legenda traduzida. No fim, ambas são portadoras de ideias, transcreva para transmiti-las e traduza para recebê-las :).
+Tenha o devido cuidado de evitar sílabas vazias, repetições ou tropeços do palestrante. Caso haja um erro óbvio, pode-se corrigi-lo, desde que a correção esteja entre colchetes, para indicar que não foi o que ele disse. Também é aceitável reescrever o que o palestrante disse em casos onde (em que) se precise adequar a legenda para que tenha velocidade de leitura e comprimento adequados. A transcrição de legendas também deve incluir informações sonoras como aplausos e risos, para os deficientes auditivos, tal como a sincronia com a fala do palestrante. Traduções ocorrem quando a palestra foi ministrada em um idioma estrangeiro que não seja o Português Brasileiro (acho que as iniciais aqui devam ser minúsculas: português brasileiro) (também estou pensando nesta frase: ministrada em um idioma estrangeiro que não seja o português brasileiro: o português não é idioma estrangeiro, pelo menos para nós), caso em que utilizamos uma transcrição do idioma original como texto base para a criação da legenda traduzida. No fim, ambas são portadoras de ideias, transcreva para transmiti-las e traduza para recebê-las :).
A mesma coisa que disse no outro, altere o que for preciso e faça os comentários fora do arquivo.In docs/transcricoes.md:>  
->> "Se ele **mantiver** essa postura, o plano pode não funcionar."
+TULIO, apesar de óbvio para nós, acho que seria bom colocar, na frente dessas frases, algo como "Correto" e "Errado"
Concordo, não estava muito satisfeito com a solução atual, essa parece boa. (Remove esse comentário do código depois :) )In docs/transcricoes.md:>  
-- Quando ficar óbvio o engano em casos como, por exemplo, o palestrante diz “baixo” claramente querendo dizer “alto”, e a edição for alterar de maneira considerável o significado da sentença, coloque a edição entre colchetes, para indicar que esta foi intencional. Exemplos:
+- Quando ficar óbvio o engano em casos como, por exemplo, o palestrante dizer “baixo” claramente querendo dizer “alto”, e a edição for alterar de maneira considerável o significado da sentença, coloque a edição entre colchetes, para indicar que esta foi intencional. Exemplos:
Não seria disser?—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2016-12-05 01:15 UTC, Raissarrm commented on docs/transcricoes.md
> +- Quando ficar óbvio o engano em casos como, por exemplo, o palestrante dizer “baixo” claramente querendo dizer “alto”, e a edição for alterar de maneira considerável o significado da sentença, coloq
Tem razão, Túlio. Disser, sem dúvida.

2016-12-05 08:28 UTC, tupaschoal commented
Closing pull request, as another one has been made.

2016-12-05 08:28 UTC, closed without merging